"""Deterministic hand-drawn map panel for the Phase 3 image composite.

The map is never generated by an image model: the geometry (places, edges,
player position) comes from the game DB, so code draws it exactly. Style is a
rough pencil sketch on parchment, tinted by game-clock time of day.

Contract: the caller passes ONLY discovered places (filtered world state, per
DESIGN.md §5) — the renderer draws what it is given and cannot leak hidden
geography. Layout is derived from a stable per-slug hash, so no layout state
needs persisting and bytes are deterministic across runs for identical input.

Stdlib + Pillow only. Font: tries a few DejaVu Serif paths, falls back to
Pillow's built-in default bitmap font (works anywhere, including the minimal
free-micro-1 image — no fonts package required).
"""

from __future__ import annotations

import hashlib
import random

from PIL import Image, ImageDraw, ImageFont

# Time-of-day palette: (parchment base, accent tint, ink)
_TOD_PALETTE = {
    "morning": ((232, 222, 196), (190, 150, 70), (60, 48, 30)),
    "midday": ((238, 230, 208), (150, 170, 120), (55, 50, 38)),
    "dusk": ((226, 206, 168), (200, 120, 55), (62, 40, 26)),
    "night": ((178, 172, 150), (60, 80, 130), (35, 32, 26)),
}

_FONT_CANDIDATES = (
    "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
)


def _load_font(px: int) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for path in _FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, px)
        except OSError:
            continue
    return ImageFont.load_default()


def _seed(text: str) -> int:
    return int.from_bytes(hashlib.md5(text.encode()).digest()[:8], "big")


def layout_map(
    places: dict[str, str],
    edges: list[tuple[str, str]],
    size: int = 1024,
) -> dict[str, tuple[float, float]]:
    """Deterministic positions for each place slug. Pure function of input.

    Spreads places on a jittered ring so maps with 2–10 places lay out without
    hand-tuning. Raises ValueError if an edge references an unknown place.
    """
    if not places:
        raise ValueError("map needs at least one place")
    for a, b in edges:
        if a not in places:
            raise ValueError(f"edge references unknown place: {a!r}")
        if b not in places:
            raise ValueError(f"edge references unknown place: {b!r}")

    slugs = sorted(places)
    n = len(slugs)
    cx = cy = size / 2
    radius = size * 0.33
    margin = size * 0.08
    positions: dict[str, tuple[float, float]] = {}
    for i, slug in enumerate(slugs):
        if n == 1:
            x, y = cx, cy
        else:
            angle = 2 * 3.141592653589793 * i / n - 3.141592653589793 / 2
            rng = random.Random(_seed("node:" + slug))
            r = radius * (0.75 + 0.35 * rng.random())
            x = cx + r * 1.15 * _cos(angle) + rng.uniform(-30, 30)
            y = cy + r * 0.90 * _sin(angle) + rng.uniform(-30, 30)
            x = min(max(x, margin), size - margin)
            y = min(max(y, margin), size - margin)
        positions[slug] = (x, y)
    return positions


def _cos(a: float) -> float:
    import math

    return math.cos(a)


def _sin(a: float) -> float:
    import math

    return math.sin(a)


def _sketch_line(
    draw: ImageDraw.ImageDraw,
    p0: tuple[float, float],
    p1: tuple[float, float],
    ink: tuple[int, int, int],
    seed_text: str,
    width: int = 3,
    passes: int = 2,
) -> None:
    """Hand-drawn line: midpoint-displaced polyline, drawn twice with offset."""
    for p in range(passes):
        rng = random.Random(_seed(seed_text) + p * 7919)
        pts = [p0]
        # subdivide into 6 segments, displace midpoints
        x0, y0 = p0
        x1, y1 = p1
        mid = [((x0 + x1) / 2, (y0 + y1) / 2)]
        for _ in range(2):
            new_mid = []
            prev = p0
            for mx, my in mid + [p1]:
                nx, ny = (prev[0] + mx) / 2, (prev[1] + my) / 2
                j = 9 if p == 0 else 5
                new_mid.append(
                    (nx + rng.uniform(-j, j), ny + rng.uniform(-j, j))
                )
                prev = (mx, my)
            mid = new_mid
        pts = [p0] + mid + [p1]
        draw.line(pts, fill=ink, width=width, joint="curve")


def _sketch_circle(
    draw: ImageDraw.ImageDraw,
    center: tuple[float, float],
    radius: float,
    ink: tuple[int, int, int],
    seed_text: str,
    width: int = 3,
) -> None:
    rng = random.Random(_seed(seed_text))
    pts = []
    import math

    for i in range(24):
        a = 2 * math.pi * i / 24
        r = radius + rng.uniform(-radius * 0.12, radius * 0.12)
        pts.append(
            (center[0] + r * math.cos(a), center[1] + r * math.sin(a))
        )
    pts.append(pts[0])
    draw.line(pts, fill=ink, width=width, joint="curve")


def render_map(
    places: dict[str, str],
    edges: list[tuple[str, str]],
    player_slug: str,
    time_of_day: str = "morning",
    size: int = 1024,
) -> Image.Image:
    """Render the map panel. Returns a PIL Image (RGB).

    places: slug -> display name (discovered places ONLY).
    edges: (from_slug, to_slug) pairs.
    player_slug: where the "YOU" pin goes; must be in places.
    time_of_day: one of morning/midday/dusk/night; tints the palette.
    """
    if player_slug not in places:
        raise ValueError(f"player place {player_slug!r} not in places")
    base, accent, ink = _TOD_PALETTE.get(time_of_day, _TOD_PALETTE["morning"])

    img = Image.new("RGB", (size, size), base)
    draw = ImageDraw.Draw(img)
    positions = layout_map(places, edges, size)

    # hand-drawn double frame
    m = size * 0.03
    _sketch_line(draw, (m, m), (size - m, m), ink, "frame:n", width=4)
    _sketch_line(draw, (size - m, m), (size - m, size - m), ink, "frame:e", width=4)
    _sketch_line(draw, (size - m, size - m), (m, size - m), ink, "frame:s", width=4)
    _sketch_line(draw, (m, size - m), (m, m), ink, "frame:w", width=4)
    m2 = size * 0.045
    _sketch_line(draw, (m2, m2), (size - m2, m2), accent, "frame2:n", width=2)
    _sketch_line(draw, (size - m2, m2), (size - m2, size - m2), accent, "frame2:e", width=2)
    _sketch_line(draw, (size - m2, size - m2), (m2, size - m2), accent, "frame2:s", width=2)
    _sketch_line(draw, (m2, size - m2), (m2, m2), accent, "frame2:w", width=2)

    # edges first (under nodes)
    for a, b in edges:
        _sketch_line(
            draw, positions[a], positions[b], ink,
            f"edge:{min(a,b)}:{max(a,b)}", width=3,
        )

    node_r = size * 0.035
    label_font = _load_font(max(20, size // 34))
    pin_font = _load_font(max(16, size // 46))
    for slug, name in places.items():
        x, y = positions[slug]
        _sketch_circle(draw, (x, y), node_r, ink, f"node:{slug}", width=3)
        # label below node, with a parchment halo so edges never strike
        # through the text
        draw.text(
            (x, y + node_r + 6), name, font=label_font, fill=ink, anchor="ma",
            stroke_width=max(2, size // 170), stroke_fill=base,
        )

    # player pin: filled red circle on their node + YOU label
    px, py = positions[player_slug]
    pin_r = node_r * 0.55
    draw.ellipse(
        [px - pin_r, py - pin_r, px + pin_r, py + pin_r],
        fill=(178, 34, 34),
        outline=(90, 16, 16),
        width=2,
    )
    draw.text(
        (px, py - node_r - 6), "YOU", font=pin_font,
        fill=(178, 34, 34), anchor="ms",
    )

    # time-of-day caption, top-left inside frame
    cap_font = _load_font(max(18, size // 40))
    draw.text(
        (size * 0.07, size * 0.055),
        time_of_day.upper(),
        font=cap_font,
        fill=accent,
        anchor="la",
    )
    return img
